addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-contrib-10
env:
  - PATH=".:/usr/lib/postgresql/10/bin:$PATH"
install: "true"
language: erlang
matrix:
  include:
    - otp_release: 22.0
    - otp_release: 21.3
    - otp_release: 20.3
    - otp_release: 19.3
    - otp_release: 18.3
      dist: trusty
script:
  - make elvis
  - make test
  - make dialyzer
